"use client";
import {useState} from 'react';
import {Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Product} from '@/lib/market';
import {toast} from 'sonner';
export default function CategoryManager({categories,products,onClose,onChanged}:{categories:string[];products:Product[];onClose:()=>void;onChanged:()=>Promise<void>}){
 const [selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const count=products.filter(p=>p.category.toLowerCase()===selected.toLowerCase()).length;
 async function remove(){if(!selected||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/categories',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:selected})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not remove this category.');await onChanged();setSelected('');toast.success('Category removed. Products are kept in Other.');}catch(e){setError(e instanceof Error?e.message:'Could not remove this category.');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="market-dialog" onInteractOutside={e=>{if(busy)e.preventDefault()}} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}}><DialogTitle>{selected?'Remove this category?':'Manage categories'}</DialogTitle><DialogDescription>{selected?`Remove “${selected}”? ${count} ${count===1?'product will':'products will'} move to Other. Products, stock counts, and past receipts are kept.`:'Remove categories you no longer need. Other is kept as the default category.'}</DialogDescription>{selected?<div className="two-buttons"><button className="button" disabled={busy} onClick={()=>{setSelected('');setError('')}}>Cancel</button><button className="button red" disabled={busy} onClick={remove}>{busy?'Removing…':'Remove category'}</button></div>:<div className="category-manager-list">{categories.map(c=><div key={c}><span><strong>{c}</strong><small>{products.filter(p=>p.category.toLowerCase()===c.toLowerCase()).length} products</small></span><button className="button" disabled={c==='Other'} aria-label={`Remove category ${c}`} onClick={()=>setSelected(c)}><Trash2 size={16}/>{c==='Other'?'Default':'Remove'}</button></div>)}</div>}{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
}
