import {useEffect,useState} from 'react';
import {HardDrive,Download,History,FolderOpen,Cloud,RefreshCw,Settings,LogOut} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type SyncStatus={state:string;message:string;lastSync?:string|null;pending:number;linked:boolean;url?:string;conflict?:{kind:string;id:string;message:string}};
declare global{interface Window{desktop?:{
 info:()=>Promise<{version:string;dataDirectory:string;backupWarning:string}>;setDraft:(value:boolean)=>Promise<void>;
 backup:()=>Promise<{ok?:boolean;canceled?:boolean;error?:string;path?:string}>;restore:()=>Promise<{ok?:boolean;canceled?:boolean;error?:string}>;openDataFolder:()=>Promise<string>;
 syncStatus:()=>Promise<SyncStatus>;connect:(url:string)=>Promise<{error?:string}>;sync:(join?:boolean)=>Promise<SyncStatus>;resolve:(choice:'online'|'local')=>Promise<SyncStatus>;disconnect:()=>Promise<void>;onDataChanged:(callback:()=>void)=>()=>void;
}}}
export default function DesktopTools({hasDraft}:{hasDraft:boolean}){
 const [busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState(''),[sync,setSync]=useState<SyncStatus>({state:'disconnected',message:'Saved on this computer',pending:0,linked:false});
 useEffect(()=>{window.desktop?.setDraft(hasDraft).catch(()=>{});},[hasDraft]);
 useEffect(()=>{
  if(!window.desktop)return;
  window.desktop.info().then(info=>{if(info.backupWarning)toast.error(info.backupWarning)}).catch(()=>{});
  const update=()=>window.desktop?.syncStatus().then(s=>{setSync(s);setUrl(u=>u||s.url||'')}).catch(()=>{});update();const timer=setInterval(update,3000);
  const unsubscribe=window.desktop.onDataChanged(()=>{window.dispatchEvent(new Event('shanti-data-changed'));update()});return()=>{clearInterval(timer);unsubscribe()};
 },[]);
 async function action(kind:'backup'|'restore'){setBusy(true);try{const r=await window.desktop?.[kind]();if(r?.error)toast.error(r.error);else if(r?.ok&&kind==='backup')toast.success('Backup saved. Keep a copy on a USB drive.')}catch{toast.error('The operation could not be completed.')}finally{setBusy(false)}}
 async function connect(){setError('');setBusy(true);try{const r=await window.desktop?.connect(url);if(r?.error)throw new Error(r.error);setSettings(false)}catch(e){setError(e instanceof Error?e.message:'Could not connect.')}finally{setBusy(false)}}
 async function doSync(join=false){setBusy(true);try{setSync(await window.desktop!.sync(join))}catch(e){toast.error(e instanceof Error?e.message:'Could not sync.')}finally{setBusy(false)}}
 async function resolve(choice:'online'|'local'){setBusy(true);try{setSync(await window.desktop!.resolve(choice))}catch(e){toast.error(e instanceof Error?e.message:'Could not resolve edit.')}finally{setBusy(false)}}
 if(!window.desktop)return <div className="desktop-tools"><span><Cloud size={16}/>Online edition <i>·</i> Changes save to your shop database</span><button onClick={async()=>{await fetch('/api/logout',{method:'POST'});location.reload()}}><LogOut size={15}/>Sign out</button></div>;
 return <><div className="desktop-tools"><span><HardDrive size={16}/>Windows edition <i>·</i> {sync.linked?sync.message:'Saved on this computer'}{sync.pending>0&&` · ${sync.pending} waiting`}</span><div><button disabled={busy} onClick={()=>action('backup')}><Download size={15}/>Back up data</button><button disabled={busy||hasDraft} title={hasDraft?'Finish or clear the current sale first':'Restore a saved backup'} onClick={()=>action('restore')}><History size={15}/>Restore</button><button onClick={()=>window.desktop?.openDataFolder()} aria-label="Open data folder"><FolderOpen size={16}/></button><button onClick={()=>{setError('');setSettings(true)}}><Settings size={15}/>{sync.url?'Sync settings':'Connect website'}</button>{sync.url&&<button disabled={busy||sync.state==='syncing'} onClick={()=>doSync()}><RefreshCw size={15}/>Sync now</button>}</div></div>
 {sync.url&&['offline','sign-in','conflict','join-required'].includes(sync.state)&&<div className={`sync-message ${sync.state==='conflict'?'error':''}`} role="status"><span>{sync.message}</span>{sync.state==='sign-in'&&<button onClick={()=>window.desktop?.connect(sync.url!)}>Sign in</button>}{sync.state==='conflict'&&sync.conflict?.kind==='product'&&<><button disabled={busy} onClick={()=>resolve('local')}>Keep this computer’s edit</button><button disabled={busy} onClick={()=>resolve('online')}>Use online edit</button></>}</div>}
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="market-dialog"><DialogTitle>Connect your shop.</DialogTitle><DialogDescription>Your Windows register keeps working offline. Changes sync when internet is available and whenever you open the app.</DialogDescription><div className="sync-form"><label className="form-label">Website address<input className="field-input" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-register.vercel.app"/></label><p>Sign in with your shop password. The first connection imports this computer’s current inventory and receipts into an empty online register.</p><button className="button red full" disabled={busy||!url.trim()} onClick={connect}><Cloud size={18}/>Connect & sign in</button>{sync.state==='join-required'&&<><p>The website already has shop data. Downloading it replaces this computer’s inventory and receipts. A safety backup is created first.</p><button className="button" disabled={busy||hasDraft} onClick={()=>doSync(true)}>Download online data</button></>}{sync.linked&&<><p>{sync.pending?`${sync.pending} changes waiting to upload.`:'No changes waiting to upload.'}{sync.lastSync&&` Last synced ${new Date(sync.lastSync).toLocaleString()}.`}</p><button className="text-button" disabled={busy||sync.pending>0} onClick={async()=>{try{await window.desktop!.disconnect();setSync(await window.desktop!.syncStatus());setSettings(false)}catch(e){setError(e instanceof Error?e.message:'Could not disconnect.')}}}>Disconnect this computer</button></>}{error&&<p className="form-error" role="alert">{error}</p>}</div></DialogContent></Dialog></>;
}
