"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Upload, ScanLine, Printer, Download, Banknote, CreditCard, Check, ArrowRight, LoaderCircle, Package } from "lucide-react";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { Product,CartLine,Sale,decimalToCents,money,totals } from "@/lib/market";
import { toast } from "sonner";
import {printElement} from "@/lib/print";
import CategoryEditor from "./category-editor";
import PhotoPicker from "./photo-picker";

export function Scanner({open,onClose,onScan}:{open:boolean;onClose:()=>void;onScan:(code:string)=>boolean}) {
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(false);
 const [running,setRunning]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState(""),[code,setCode]=useState("");
 const stop=()=>{alive.current=false;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearTimeout(timer.current);setRunning(false);setStarting(false)};
 useEffect(()=>{if(!open)stop();return()=>{alive.current=false;stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearTimeout(timer.current)}},[open]);
 const scan=(value:string)=>{if(onScan(value.trim())){stop();onClose()}else{stop();setError(`No available product found for “${value.slice(0,80)}”. Check its code in Inventory.`)}};
 async function start(){
  setError("");setStarting(true);alive.current=true;
  try{
   if(!navigator.mediaDevices?.getUserMedia)throw new Error("Camera access is unavailable here. Upload a QR image or enter the product code below.");
   const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280}},audio:false});
   if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}
   stream.current=media;if(!video.current){stop();return;}video.current.srcObject=media;await video.current.play();setRunning(true);setStarting(false);
   const jsQR=(await import("jsqr")).default;const canvas=document.createElement("canvas");const ctx=canvas.getContext("2d",{willReadFrequently:true});
   const tick=()=>{if(!alive.current||!video.current||!ctx)return;const v=video.current;if(v.readyState>=2&&v.videoWidth){const scale=Math.min(1,800/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);ctx.drawImage(v,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const found=jsQR(pixels.data,pixels.width,pixels.height);if(found){scan(found.data);return;}}timer.current=setTimeout(tick,180)};tick();
  }catch(e){stop();setError(e instanceof Error&&e.name==="NotAllowedError"?"Camera permission was declined. Allow camera access in your browser, or upload a QR image below.":e instanceof Error&&e.name==="NotFoundError"?"No camera was found. Upload a QR image or type the code instead.":e instanceof Error?e.message:"The camera could not start.")}
 }
 async function readFile(file:File|undefined){
  if(!file)return;stop();setError("");if(file.size>12*1024*1024){setError("Choose an image smaller than 12 MB.");return;}
  const url=URL.createObjectURL(file);
  try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement("canvas");const scale=Math.min(1,1600/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Image reading is unavailable.");ctx.drawImage(img,0,0,canvas.width,canvas.height);const data=ctx.getImageData(0,0,canvas.width,canvas.height);const jsQR=(await import("jsqr")).default;const found=jsQR(data.data,data.width,data.height);if(found)scan(found.data);else setError("No QR code detected. Try a clear, close-up photo with the whole QR code visible.")}
  catch{setError("This image could not be read. Try a PNG or JPEG.")}finally{URL.revokeObjectURL(url)}
 }
 return <Dialog open={open} onOpenChange={v=>{if(!v){stop();onClose()}}}><DialogContent className="market-dialog"><DialogTitle>Scan a little goodness.</DialogTitle><DialogDescription>Point the camera at a product QR code to add one item.</DialogDescription><div className={`camera-area ${running?"running":""}`}><video ref={video} muted playsInline autoPlay aria-label="QR camera preview"/>{!running&&<div><ScanLine size={54}/><p>Keep the QR code inside the frame</p></div>}{running&&<span className="camera-hint">Looking for a QR code…</span>}</div><div className="two-buttons"><button className="button red" disabled={starting} onClick={running?stop:start}><Camera size={18}/>{starting?"Starting…":running?"Stop camera":"Start camera"}</button><label className="button upload-button"><Upload size={18}/>Upload QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{readFile(e.target.files?.[0]);e.target.value=""}}/></label></div><form onSubmit={e=>{e.preventDefault();scan(code)}} className="manual-scan"><label htmlFor="manual-code">Or enter the product code</label><div className="search-row"><input className="field-input" id="manual-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="e.g. SV-001" maxLength={500}/><button className="button" disabled={!code.trim()} type="submit">Add item <ArrowRight size={16}/></button></div></form>{error&&<p className="form-error" role="alert">{error}</p>}<p className="fine-print">A USB scanner can also type into the product search. QR codes can contain a register code or the original shop product link.</p></DialogContent></Dialog>
}

export function ProductEditor({product,onClose,onSaved,categories,onCategoriesChanged}:{product:Product|"new";onClose:()=>void;onSaved:()=>Promise<void>;categories:string[];onCategoriesChanged:(names:string[])=>void}){
 const [categoryEditor,setCategoryEditor]=useState(false);
 const p=product==="new"?null:product;
 const [name,setName]=useState(p?.name||""),[code,setCode]=useState(p?.code||""),[category,setCategory]=useState(categories.find(c=>c.toLowerCase()===p?.category.toLowerCase())||p?.category||categories[0]||"Other"),[unit,setUnit]=useState(p?.unit||"1 piece"),[price,setPrice]=useState(p?(p.price/100).toFixed(2):""),[stock,setStock]=useState(String(p?.stock??0)),[tracked,setTracked]=useState(p?!!p.stockTracked:true),[available,setAvailable]=useState(p?!!p.available:true);
 const [image,setImage]=useState(p?.image||""),[photoBusy,setPhotoBusy]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(e:React.FormEvent){e.preventDefault();if(photoBusy||busy)return;const cents=decimalToCents(price);if(cents===null||cents<=0||cents>10000000){setError("Enter a price from $0.01 to $100,000.00, with at most two decimal places.");return;}if(tracked&&(!/^\d+$/.test(stock)||Number(stock)>1000000)){setError("Stock must be a whole number between 0 and 1,000,000.");return;}setBusy(true);setError("");
 try{const icon=p?.icon||({"Raw crystals":"gem","Incense holders":"sparkles","Incense sticks":"leaf"}[category]||"basket");const response=await fetch('/api/products',{method:p?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...(p?{id:p.id,version:p.version}:{}),name,code,category,unit,price:cents,stock:tracked?Number(stock):p?.stock??0,stockTracked:tracked?1:0,available:available?1:0,icon,image})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Could not save this product.");await onSaved();toast.success(p?"Product updated":"New product added");onClose()}catch(e){setError(e instanceof Error?e.message:"Could not save this product.")}finally{setBusy(false)}}
 return <><Dialog open onOpenChange={v=>{if(!v&&!busy&&!photoBusy&&!categoryEditor)onClose()}}><DialogContent className="market-dialog" onInteractOutside={e=>{if(busy||photoBusy)e.preventDefault()}}><DialogTitle>{p?"Edit the essentials.":"Something new on the shelf."}</DialogTitle><DialogDescription>{p?"Update the details, price, or current stock count.":"Add a product to the inventory. Its code connects it to the register."}</DialogDescription><form onSubmit={save} className="product-form"><PhotoPicker image={image} onChange={setImage} onBusy={setPhotoBusy} disabled={busy}/><label>Product name<input required maxLength={80} className="field-input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Rose quartz"/></label><div className="form-columns"><label>Product / QR code<input required className="field-input mono" maxLength={80} pattern="[A-Za-z0-9._\-]+" value={code} onChange={e=>setCode(e.target.value)} placeholder="e.g. SV-028"/></label><label>Category<select name="category" className="field-input" value={category} onChange={e=>setCategory(e.target.value)}>{Array.from(new Set([...categories,category])).map(c=><option key={c} value={c}>{c}</option>)}</select><button type="button" className="text-button add-category-inline" disabled={busy} onClick={()=>setCategoryEditor(true)}>+ Add category</button></label></div><label>Pack size / unit<input className="field-input" required maxLength={40} value={unit} onChange={e=>setUnit(e.target.value)} placeholder="e.g. 1 piece"/></label><div className="form-columns"><label>Price (USD)<input className="field-input" required inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0.00"/></label><label>Units in stock<input className="field-input" disabled={!tracked} required={tracked} inputMode="numeric" value={tracked?stock:""} placeholder="Count not set" onChange={e=>setStock(e.target.value)}/></label></div><div className="stock-options"><label><Checkbox checked={tracked} onCheckedChange={v=>setTracked(v===true)}/>Track stock quantities</label><label><Checkbox checked={available} onCheckedChange={v=>setAvailable(v===true)}/>Available for sale</label></div><p className="fine-print">The storefront does not reveal stock counts. Untracked products can be sold without deducting a quantity. Enable tracking and enter the actual count to prevent overselling.</p>{p?.sourceUrl&&<a className="source-link" href={p.sourceUrl} target="_blank" rel="noopener noreferrer">View original product ↗</a>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button red full" disabled={busy||photoBusy}>{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy?"Saving…":"Save product"}</button></form></DialogContent></Dialog>{categoryEditor&&<CategoryEditor categories={categories} onClose={()=>setCategoryEditor(false)} onSaved={(name,names)=>{onCategoriesChanged(names);setCategory(name)}}/>}</>
}

export function Checkout({cart,discountRate,taxRate,onClose,onComplete,onConflict}:{cart:CartLine[];discountRate:number;taxRate:number;onClose:()=>void;onComplete:(sale:Sale)=>void;onConflict:()=>void}){
 const amounts=totals(cart.map(l=>({price:l.product.price,quantity:l.quantity})),discountRate,taxRate);
 const [payment,setPayment]=useState("cash"),[cash,setCash]=useState((amounts.total/100).toFixed(2)),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [frozen,setFrozen]=useState(false);const payload=useRef<string|null>(null);const sent=useRef(false);
 const tendered=decimalToCents(cash),change=(tendered??0)-amounts.total;
 async function complete(){if(sent.current)return;if(!payload.current&&payment==="cash"&&(tendered===null||change<0)){setError("Enter enough cash to cover the total.");return;}sent.current=true;setBusy(true);setError("");setFrozen(true);
 if(!payload.current)payload.current=JSON.stringify({id:crypto.randomUUID(),items:cart.map(l=>({id:l.product.id,quantity:l.quantity,expectedPrice:l.product.price})),discountRate,taxRate,payment,tendered:payment==="cash"?tendered:amounts.total});
 try{const r=await fetch('/api/sales',{method:"POST",headers:{"Content-Type":"application/json"},body:payload.current});const data=await r.json() as {error?:string;sale:Sale};if(!r.ok){if(r.status<500){payload.current=null;setFrozen(false);if(r.status===409)onConflict()}throw new Error(data.error||"Could not confirm this sale. Retry safely.");}onComplete(data.sale)}catch(e){setError(e instanceof Error?e.message:"Connection interrupted. Retry this checkout; the sale will only be recorded once.")}finally{sent.current=false;setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy&&!frozen)onClose()}}><DialogContent className="market-dialog" showCloseButton={!frozen} onEscapeKeyDown={e=>{if(frozen)e.preventDefault()}} onInteractOutside={e=>{if(frozen)e.preventDefault()}}><DialogTitle>That’s everything.</DialogTitle><DialogDescription>{cart.reduce((s,l)=>s+l.quantity,0)} items · Choose how this sale was paid.</DialogDescription><div className="checkout-total"><span>AMOUNT DUE</span><strong>{money(amounts.total)}</strong></div><RadioGroup value={payment} onValueChange={setPayment} disabled={frozen} className="payment-options"><label className={payment==="cash"?"selected":""}><RadioGroupItem value="cash"/><Banknote size={21}/>Cash</label><label className={payment==="card"?"selected":""}><RadioGroupItem value="card"/><CreditCard size={21}/>Card</label></RadioGroup>{payment==="cash"?<><label className="form-label">Cash received (USD)<input autoFocus className="field-input" inputMode="decimal" value={cash} disabled={frozen} onChange={e=>setCash(e.target.value)}/></label><div className="cash-shortcuts">{Array.from(new Set([amounts.total,2000,5000,10000])).filter(v=>v>=amounts.total).map(v=><button key={v} className="button" disabled={frozen} onClick={()=>setCash((v/100).toFixed(2))}>{v===amounts.total?"Exact":money(v)}</button>)}</div><div className="change-line"><span>Change to give</span><strong>{money(Math.max(0,change))}</strong></div></>:<p className="terminal-note">Complete payment on your separate card terminal first. This register records the payment; it does not charge a card.</p>}{error&&<p className="form-error" role="alert">{error}</p>}{frozen&&!busy&&<p className="fine-print">Keep this checkout open and retry to confirm its status safely.</p>}<button className="button red full" disabled={busy||(!frozen&&payment==="cash"&&(tendered===null||change<0))} onClick={complete}>{busy?<LoaderCircle size={19} className="spin"/>:<Check size={19}/>} {busy?"Recording sale…":frozen?"Retry & confirm sale":"Complete sale"}</button></DialogContent></Dialog>
}

export function Receipt({sale,onClose}:{sale:Sale;onClose:()=>void}){
 const printRef=useRef<HTMLDivElement>(null);const [printing,setPrinting]=useState(false);
 async function print(){if(!printRef.current||printing)return;setPrinting(true);try{await printElement(printRef.current)}catch{toast.error("Could not open printing. Please try again.")}finally{setPrinting(false)}}
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="market-dialog receipt-dialog"><DialogTitle className="sr-only">Receipt {sale.number}</DialogTitle><DialogDescription className="sr-only">Completed sale receipt</DialogDescription><div ref={printRef} className="print-target final-receipt"><div className="receipt-stamp"><Check size={18}/>PAID</div><p className="eyebrow">THE SHOP REGISTER</p><h2>{sale.shopName}</h2><p className="receipt-thanks">A little calm, to take with you.</p><div className="receipt-meta"><span>RECEIPT {sale.reference? sale.reference.slice(0,15):`#${String(sale.number).padStart(5,"0")}`}</span><span>{sale.payment.toUpperCase()}</span></div>{sale.reference&&<p className="receipt-reference">{sale.reference}</p>}<p className="receipt-date">{new Date(sale.createdAt).toLocaleString()}</p><div className="printed-items">{sale.items.map((i,index)=><div key={index}><span>{i.name}<small>{i.quantity} × {money(i.price)}</small></span><strong>{money(i.quantity*i.price)}</strong></div>)}</div><div className="receipt-closing"><div className="receipt-summary"><div><span>Subtotal</span><span>{money(sale.subtotal)}</span></div>{sale.discount>0&&<div><span>Discount ({sale.discountRate/100}%)</span><span>−{money(sale.discount)}</span></div>}<div><span>Tax ({sale.taxRate/100}%)</span><span>{money(sale.tax)}</span></div></div><div className="total-line"><span>Total</span><strong>{money(sale.total)}</strong></div>{sale.payment==="cash"&&<div className="receipt-summary"><div><span>Cash received</span><span>{money(sale.tendered)}</span></div><div><span>Change</span><span>{money(sale.tendered-sale.total)}</span></div></div>}<div className="receipt-end">THANK YOU FOR SHOPPING WITH US.<br/><span>May your day be a little brighter.</span></div></div></div><div className="two-buttons no-print"><button className="button" disabled={printing} onClick={print}><Printer size={17}/>{printing?"Preparing…":"Print receipt"}</button><button className="button red" onClick={onClose}>Back to register <ArrowRight size={17}/></button></div></DialogContent></Dialog>
}

export function QRLabel({product,onClose}:{product:Product;onClose:()=>void}){
 const printRef=useRef<HTMLDivElement>(null);
 const [url,setUrl]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let active=true;import("qrcode").then(q=>q.toDataURL(product.code,{width:480,margin:4,errorCorrectionLevel:"M",color:{dark:"#342922",light:"#ffffff"}})).then(u=>{if(active)setUrl(u)}).catch(()=>{if(active)setError("This QR label could not be generated. Close and try again.")});return()=>{active=false}},[product.code]);
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="market-dialog"><DialogTitle>A label for the shelf.</DialogTitle><DialogDescription>Scan this QR code at the register to add this product.</DialogDescription><div ref={printRef} className="qr-label print-target"><p className="eyebrow">SHANTI VIKĀSA</p>{url?<img src={url} width={240} height={240} alt={`QR code for ${product.name}: ${product.code}`}/>:<div className="qr-loading"><Package size={40}/></div>}<h3>{product.name}</h3><p>{product.unit} · {money(product.price)}</p><strong>{product.code}</strong></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="two-buttons no-print"><button className="button" disabled={!url} onClick={()=>{if(printRef.current)printElement(printRef.current).catch(()=>toast.error("Could not open printing. Please try again."))}}><Printer size={17}/>Print label</button>{url&&<a className="button red" href={url} download={`qr-${product.code}.png`}><Download size={17}/>Download QR</a>}</div></DialogContent></Dialog>
}
