"use client";
import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,Download,RefreshCw,Search} from 'lucide-react';
import {money,Sale} from '@/lib/market';
import {downloadCSV} from '@/lib/csv';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
type Item={id:string;name:string;code:string;category:string;unitsSold:number;itemSales:number;stock:number|null;archived:boolean;available:boolean;price:number};
type Report={period:string;date:string;timeZone:string;start:string;end:string;summary:{receipts:number;unitsSold:number;grossSales:number;discounts:number;netSales:number;tax:number;totalCollected:number;cash:number;card:number;averageSale:number};inventory:{products:number;countedUnits:number;retailValue:number;uncountedProducts:number;lowStock:number;outOfStock:number};daily:{date:string;receipts:number;unitsSold:number;netSales:number;tax:number;totalCollected:number}[];items:Item[];sales:Sale[]};
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
const dollars=(n:number)=>(n/100).toFixed(2);
export default function SalesReports({onReceipt}:{onReceipt:(s:Sale)=>void}){
 const [period,setPeriod]=useState('day'),[date,setDate]=useState(today),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[search,setSearch]=useState(''),[soldOnly,setSoldOnly]=useState(false),[page,setPage]=useState(0);
 const reload=useCallback(()=>setRefresh(v=>v+1),[]);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setReport(current=>current&&current.period===period&&current.date===date?current:null);if(!date){setBusy(false);return;}
  const params=new URLSearchParams({period,date,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone});
  fetch('/api/reports?'+params,{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load reports.');setReport(d);setPage(p=>Math.min(p,Math.max(0,Math.ceil(d.sales.length/25)-1)));}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort();
 },[period,date,refresh]);
 useEffect(()=>{window.addEventListener('shanti-sales-changed',reload);const timer=setInterval(()=>{if(!document.hidden)reload()},60000);return()=>{window.removeEventListener('shanti-sales-changed',reload);clearInterval(timer)}},[reload]);
 const s=report?.summary,inv=report?.inventory,rows=report?.items.filter(p=>(!soldOnly||p.unitsSold>0)&&`${p.name} ${p.code} ${p.category}`.toLowerCase().includes(search.toLowerCase()))||[];
 function exportReport(){if(!report)return;downloadCSV(`shanti-report-${report.start}-${report.end}.csv`,[['REPORT',report.start,report.end,report.timeZone],['Metric','Value'],['Receipts',report.summary.receipts],['Units sold',report.summary.unitsSold],['Gross sales (USD)',dollars(report.summary.grossSales)],['Discounts (USD)',dollars(report.summary.discounts)],['Net sales before tax (USD)',dollars(report.summary.netSales)],['Tax (USD)',dollars(report.summary.tax)],['Total collected (USD)',dollars(report.summary.totalCollected)],['Cash sales (USD)',dollars(report.summary.cash)],['Card sales (USD)',dollars(report.summary.card)],[],['Product','Code','Category','Units sold','Item sales before discounts/tax (USD)','Stock now','Status'],...report.items.map(p=>[p.name,p.code,p.category,p.unitsSold,dollars(p.itemSales),p.archived?'Removed':p.stock??'Not counted',p.archived?'Removed':p.available?'Available':'Unavailable']),[],['Date','Receipts','Units sold','Net sales (USD)','Tax (USD)','Collected (USD)'],...report.daily.map(d=>[d.date,d.receipts,d.unitsSold,dollars(d.netSales),dollars(d.tax),dollars(d.totalCollected)])]);}
 return <section className="wide-page sales-reports"><div className="section-heading"><div><p className="eyebrow">KEEPING THE BOOKS</p><h2>Sales & stock.</h2></div><div className="category-actions"><button className="button" disabled={busy} onClick={reload}><RefreshCw size={16}/>Refresh</button><button className="button" disabled={!report||busy} onClick={exportReport}><Download size={16}/>Export report</button></div></div>
 <div className="report-controls"><div className="report-periods" aria-label="Report period">{[['day','Daily'],['week','Weekly'],['month','Monthly']].map(([value,label])=><button key={value} aria-pressed={period===value} className={`button ${period===value?'red':''}`} onClick={()=>{setPeriod(value);setPage(0)}}>{label}</button>)}</div><label>Report date<input className="field-input" type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(0)}}/></label><button className="text-button" onClick={()=>setDate(today())}>Today</button></div>
 {error&&<div className="error-banner" role="alert">{error}<button className="button" onClick={reload}>Retry</button></div>}{busy&&<p role="status">Loading your report…</p>}{report&&s&&inv&&<><p className="fine-print">{report.start} → {report.end} · {report.timeZone}{period==='week'?' · Monday to Sunday':''}. Sales reflect this period; stock shows the current count.</p>
 <div className="report-cards">{[['TOTAL COLLECTED',money(s.totalCollected)],['NET SALES · BEFORE TAX',money(s.netSales)],['RECEIPTS',String(s.receipts)],['UNITS SOLD',String(s.unitsSold)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 <div className="report-details"><div><h3>Money in the register</h3><dl>{[['Sales before discounts',money(s.grossSales)],['Discounts',money(s.discounts)],['Tax collected',money(s.tax)],['Cash sales · after change',money(s.cash)],['Card sales',money(s.card)],['Average receipt',money(s.averageSale)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div><h3>On the shelves now</h3><dl>{[['Products',inv.products],['Counted units',inv.countedUnits],['Low stock · 8 or fewer',inv.lowStock],['Out of stock',inv.outOfStock],['Products needing a count',inv.uncountedProducts],['Stock value · selling prices',money(inv.retailValue)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="fine-print">Stock value covers counted products at current selling prices. It is not profit; purchase costs and expenses are not recorded.</p></div></div>
 <h3 className="report-heading">What sold & what remains</h3><div className="inventory-tools"><div className="search-field"><Search size={18}/><input aria-label="Search report products" placeholder="Search product, code, or category…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className={`button ${soldOnly?'red':''}`} aria-pressed={soldOnly} onClick={()=>setSoldOnly(!soldOnly)}>Sold in this period</button></div><div className="table-frame"><Table><TableHeader><TableRow><TableHead>PRODUCT</TableHead><TableHead>UNITS SOLD</TableHead><TableHead>ITEM SALES*</TableHead><TableHead>STOCK NOW</TableHead></TableRow></TableHeader><TableBody>{rows.map(p=><TableRow key={p.id}><TableCell><strong>{p.name}</strong><div className="fine-print">{p.code} · {p.category}{p.archived?' · Removed':''}</div></TableCell><TableCell>{p.unitsSold}</TableCell><TableCell>{money(p.itemSales)}</TableCell><TableCell>{p.archived?'Removed':p.stock===null?'Not counted':p.stock}{!p.archived&&!p.available?' · Unavailable':''}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="report-empty">No products match this view.</p>}</div><p className="fine-print">* Item sales use the prices recorded on receipts, before receipt-level discounts and tax.</p>
 {period!=='day'&&<><h3 className="report-heading">Daily breakdown</h3><div className="table-frame"><Table><TableHeader><TableRow><TableHead>DATE</TableHead><TableHead>RECEIPTS</TableHead><TableHead>UNITS</TableHead><TableHead>NET SALES</TableHead><TableHead>COLLECTED</TableHead></TableRow></TableHeader><TableBody>{report.daily.map(d=><TableRow key={d.date}><TableCell>{d.date}</TableCell><TableCell>{d.receipts}</TableCell><TableCell>{d.unitsSold}</TableCell><TableCell>{money(d.netSales)}</TableCell><TableCell>{money(d.totalCollected)}</TableCell></TableRow>)}</TableBody></Table></div></>}
 <div className="section-heading report-heading"><h3>Receipts in this period</h3><button className="button" disabled={!report.sales.length} onClick={()=>downloadCSV(`shanti-receipts-${report.start}-${report.end}.csv`,[['Receipt','Date (UTC)','Payment','Subtotal (USD)','Discount (USD)','Tax (USD)','Total (USD)'],...report.sales.map(s=>[s.reference||s.number,s.createdAt,s.payment,dollars(s.subtotal),dollars(s.discount),dollars(s.tax),dollars(s.total)])])}><Download size={16}/>Export receipts</button></div><div className="table-frame"><Table><TableHeader><TableRow><TableHead>RECEIPT</TableHead><TableHead>DATE & TIME</TableHead><TableHead>ITEMS</TableHead><TableHead>PAYMENT</TableHead><TableHead>TOTAL</TableHead><TableHead>DETAILS</TableHead></TableRow></TableHeader><TableBody>{report.sales.slice(page*25,(page+1)*25).map(s=><TableRow key={s.id}><TableCell className="mono">{s.reference?s.reference.slice(0,15):`#${String(s.number).padStart(5,'0')}`}</TableCell><TableCell>{new Date(s.createdAt).toLocaleString()}</TableCell><TableCell>{s.items.reduce((n,i)=>n+i.quantity,0)}</TableCell><TableCell>{s.payment}</TableCell><TableCell>{money(s.total)}</TableCell><TableCell><button className="text-button" onClick={()=>onReceipt(s)}>View receipt <ArrowRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>{!report.sales.length&&<p className="report-empty">No completed sales in this period.</p>}</div>{report.sales.length>25&&<div className="report-pagination"><button className="button" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} of {Math.ceil(report.sales.length/25)}</span><button className="button" disabled={(page+1)*25>=report.sales.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}
 </section>
}
