import {useEffect,useState} from 'react';
import {LoaderCircle,LockKeyhole} from 'lucide-react';
import Register from './register';
export default function SessionGate(){
 const [status,setStatus]=useState<'loading'|'login'|'ready'|'setup'|'error'>(window.desktop?'ready':'loading'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function check(){try{const r=await fetch('/api/session');if(!r.ok)throw new Error();const s=await r.json();setStatus(!s.configured?'setup':s.authenticated?'ready':'login');}catch{setStatus('error');}}
 useEffect(()=>{if(!window.desktop)check()},[]);
 async function login(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not sign in.');setPassword('');setStatus('ready');}catch(e){setError(e instanceof Error?e.message:'Could not sign in.')}finally{setBusy(false)}}
 if(status==='ready')return <Register/>;
 return <main className="login-surface"><section className="login-card"><img src="/shanti-logo.png" alt="Shanti Vikasa"/><h1>Your shop register.</h1>{status==='loading'?<p><LoaderCircle className="spin"/> Opening your register…</p>:status==='setup'?<><p>The website is installed. Connect its online database and set the shop password to start syncing.</p><p>Your Windows inventory stays saved on your computer until you connect it.</p><button className="button" onClick={check}>Check again</button></>:status==='error'?<><p>The website could not connect. Check your internet connection and try again.</p><button className="button" onClick={check}>Try again</button></>:<><p>Sign in to manage inventory and view sales.</p><form onSubmit={login}><label className="form-label">Shop password<input className="field-input" type="password" autoComplete="current-password" autoFocus required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button red full" disabled={busy}><LockKeyhole size={17}/>{busy?'Signing in…':'Open register'}</button></form></>}</section></main>;
}
