'use strict';
// Run with an official Electron runtime. All app data is isolated in a temporary directory.
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'shanti-native-ui-')),stage=path.join(temp,'app'),output=path.join(root,'qa-artifacts');
fs.mkdirSync(stage,{recursive:true});fs.mkdirSync(output,{recursive:true});
for(const name of ['desktop','shared','data'])fs.cpSync(path.join(root,name),path.join(stage,name),{recursive:true});
fs.cpSync(path.join(root,'dist-desktop'),path.join(stage,'dist'),{recursive:true});fs.mkdirSync(path.join(stage,'public'));fs.copyFileSync(path.join(root,'public/shanti-logo.png'),path.join(stage,'public/shanti-logo.png'));
fs.mkdirSync(path.join(temp,'appdata'));fs.mkdirSync(path.join(temp,'userdata'));app.setPath('userData',path.join(temp,'userdata'));app.setPath('appData',path.join(temp,'appdata'));app.disableHardwareAcceleration();
require(path.join(stage,'desktop/main.cjs'));
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const deadline=setTimeout(()=>{console.error('Native UI verification timed out');app.exit(1)},90000);
(async()=>{
 await app.whenReady();let win;for(let i=0;i<100;i++){win=BrowserWindow.getAllWindows()[0];if(win)break;await delay(100);}assert(win,'Main window did not open');
 const evaluate=code=>win.webContents.executeJavaScript(code,true);
 async function waitFor(code){for(let i=0;i<100;i++){try{if(await evaluate(code))return;}catch{}await delay(100);}throw new Error('UI condition timed out: '+code);}
 async function click(text){
  const locate=`(()=>{const scope=[...document.querySelectorAll('[role=dialog][data-state=open]')].at(-1)||document;const e=[...scope.querySelectorAll('button')].find(e=>e.getBoundingClientRect().width&&e.textContent.trim()===${JSON.stringify(text)});if(!e||e.disabled)return null;e.scrollIntoView({block:'center',behavior:'instant'});const r=e.getBoundingClientRect();return{x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)}})()`;
  assert(await evaluate(locate),'Missing button '+text);await delay(250);const point=await evaluate(locate);assert(point,'Missing button '+text);win.focus();win.webContents.focus();
  for(const type of ['mouseMove','mouseDown','mouseUp'])win.webContents.sendInputEvent({type,...point,button:'left',clickCount:1});await delay(200);
 }
 async function input(placeholder,value){await evaluate(`(()=>{const e=document.querySelector('input[placeholder=${JSON.stringify(placeholder)}]');if(!e)throw new Error('Input not found');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);await delay(100);}
 await waitFor("!!document.querySelector('.market-app') && !!document.querySelector('.product-card')");
 assert((await evaluate('window.desktop.info()')).dataDirectory.startsWith(temp),'Test attempted to use a non-test database');
 await click('Inventory');await waitFor("!!document.querySelector('button[role=tab][data-state=active][data-value=inventory]') || [...document.querySelectorAll('[role=tab][data-state=active]')].some(e=>e.textContent==='Inventory')");await click('Add category');await input('e.g. Candles','QA candles');await click('Add category');await waitFor("!document.querySelector('[role=dialog]')");
 assert(await evaluate("fetch('/api/categories').then(r=>r.json()).then(d=>d.categories.includes('QA candles'))"));
 // Verify the nested category editor leaves the unsaved product form intact.
 await click('New product');await input('e.g. Rose quartz','Unsaved test product');await click('+ Add category');await input('e.g. Candles','QA gifts');await click('Add category');await waitFor("document.querySelector('select[name=category]')?.value==='QA gifts'");assert.equal(await evaluate("document.querySelector('input[placeholder=\"e.g. Rose quartz\"]').value"),'Unsaved test product');await evaluate("[...document.querySelectorAll('[role=dialog] button')].find(e=>e.textContent.trim()==='Close').click()");await waitFor("!document.querySelector('[role=dialog]')");
 // Create a known receipt via the actual desktop API, then inspect the normal report UI.
 const sale=await evaluate(`(async()=>{const products=(await(await fetch('/api/products')).json()).products;const p=products[0];await fetch('/api/products',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,name:'Print-check Candle',category:'QA candles',price:1250,stockTracked:1,stock:8,available:1})});const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),items:[{id:p.id,quantity:2,expectedPrice:1250}],discountRate:1000,taxRate:500,payment:'cash',tendered:3000})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d.sale})()`);
 assert.equal(sale.total,2363);win.webContents.send('desktop:data-changed');await delay(300);
 await click('Manage categories');await evaluate("document.querySelector('button[aria-label=\"Remove category QA candles\"]').click()");await delay(100);await click('Remove category');await waitFor("document.querySelector('[role=dialog]')?.textContent.includes('Manage categories')");assert(await evaluate("fetch('/api/products').then(r=>r.json()).then(d=>d.products.find(p=>p.name==='Print-check Candle').category==='Other')"));await evaluate("[...document.querySelectorAll('[role=dialog] button')].find(e=>e.textContent.trim()==='Close').click()");await waitFor("!document.querySelector('[role=dialog]')");
 await click('Sales & reports');await waitFor("document.querySelector('.sales-reports')?.textContent.includes('Print-check Candle')");assert(await evaluate("document.querySelector('.report-cards').textContent.includes('$23.63')"));
 await click('Weekly');await waitFor("document.querySelector('.sales-reports')?.textContent.includes('Daily breakdown')");await click('Monthly');await waitFor("[...document.querySelectorAll('button')].some(e=>e.getBoundingClientRect().width&&e.textContent.trim()==='View receipt')");await click('View receipt');await waitFor("!!document.querySelector('.final-receipt .printed-items')");
 // Intercept only the OS dialog; the actual application's print preparation and CSS run unchanged.
 console.log("PASS: categories, nested product form, daily/weekly/monthly reports and saved receipt view.");await evaluate("window.print=()=>{};void 0;");await click('Print receipt');await waitFor("document.querySelector('#shanti-print-root .printed-items')?.textContent.includes('Print-check Candle')");
 fs.writeFileSync(path.join(output,'receipt.pdf'),await win.webContents.printToPDF({printBackground:true,pageSize:'A4'}));fs.writeFileSync(path.join(output,'receipt.png'),(await win.webContents.capturePage()).toPNG());await evaluate("window.dispatchEvent(new Event('afterprint'))");await click('Back to register');
 // A long receipt verifies pagination and prevents clipped/missing final items.
 const lastName=await evaluate(`(async()=>{const products=(await(await fetch('/api/products')).json()).products;const items=products.map(p=>({id:p.id,quantity:1,expectedPrice:p.price}));for(const p of products)if(!p.available||p.stockTracked&&p.stock<1)await fetch('/api/products',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...p,available:1,stockTracked:0})});const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),items,discountRate:0,taxRate:0,payment:'card',tendered:10000000})});if(!r.ok)throw new Error((await r.json()).error);return products[products.length-1].name})()`);
 win.webContents.send('desktop:data-changed');await waitFor("document.querySelectorAll('.sales-reports button').length>0 && [...document.querySelectorAll('.sales-reports button')].filter(e=>e.textContent.trim()==='View receipt').length===2");await click('View receipt');await click('Print receipt');await waitFor("document.querySelectorAll('#shanti-print-root .printed-items>div').length===27");fs.writeFileSync(path.join(output,'long-receipt.pdf'),await win.webContents.printToPDF({printBackground:true,pageSize:'A4'}));fs.writeFileSync(path.join(output,'expected.json'),JSON.stringify({lastName,total:'23.63'}));await evaluate("window.dispatchEvent(new Event('afterprint'))");await click('Back to register');await waitFor("!document.querySelector('[role=dialog]')");await evaluate("window.scrollTo(0,0);void 0;");await delay(250);fs.writeFileSync(path.join(output,'reports.png'),(await win.webContents.capturePage()).toPNG());await evaluate("document.querySelector('.report-details').scrollIntoView({block:'start'});void 0;");await delay(250);fs.writeFileSync(path.join(output,'report-details.png'),(await win.webContents.capturePage()).toPNG());
 console.log('PASS: native startup, category creation/removal, nested form, reports, short and long receipt print preparation.');clearTimeout(deadline);app.quit();
})().catch(async error=>{console.error(error);try{const win=BrowserWindow.getAllWindows()[0];if(win)fs.writeFileSync(path.join(output,'failure.png'),(await win.webContents.capturePage()).toPNG());}catch{}clearTimeout(deadline);app.exit(1)});
